# Generated by Django 3.1.6 on 2021-02-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210222_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
