# Generated by Django 3.1.6 on 2021-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
