# Generated by Django 3.1.6 on 2021-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='uploads/cover_photos'),
        ),
    ]
