# Generated by Django 3.1.6 on 2021-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_userprofile_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/user.png', upload_to='uploads/cover_photos'),
        ),
    ]
