# Generated by Django 3.1.6 on 2021-05-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20210519_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cover_photos'),
        ),
    ]
