# Generated by Django 3.1.6 on 2021-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20210716_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cover_photos'),
        ),
    ]
